export default {
    addMemberTitle:"Add member",
    editMemberTitle:"Edit member",
    addMemberSuccessMessage:"Member added successfully",
    updateMemberSuccessMessage:"Member details updated successfully",
    memberNameErrorMessage:"Enter member name",
    ageErrorMessage:"Enter age",
    addButtonLabel:"Add",
    editButtonLabel:"Edit",
    clearButtonLabel:"Clear",
    dateOfBirth:"Date of birth",
    dayError:"dayError",
    monthError:"monthError",
    yearError:"yearError",
    dobLabel:"DOB",
    ageLabel:"Age",
    advancedOptionsLabel:"Add more details",
    updateMobileNumberLabel:"Update mobile number",
    cancelLabel:"Cancel",
    updateLabel:"Update",
    otpNotification:"*We will send you an OTP in new number",
    updateNumberSuccess:"Your number has been updated",
    emailPlaceholder:"Enter your email here",
    qualificationPlaceholder:"Enter your qualification here",
    memberNamePlaceholder:"Enter family member name here",
    agePlaceholder:"Enter age here",
    mobileNumberPlaceholder:"Enter new mobile number",
    otpPlaceholder:"*****OTP"
}